name: Build TinyRetroPad Linux CrossCompile
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Tools and UASM
        run: |
          sudo apt-get update
          sudo apt-get install -y lld wget unzip
          # Scarica il compilatore UASM per Linux
          wget https://github.com
          unzip uasm256_linux64.zip
          chmod +x uasm

      - name: Run Build
        run: |
          # UASM compila il file ignorando il case-sensitive e senza bisogno di windows.inc esterni
          ./uasm -coff -win32 -zcm trpad.asm
          # Effettua il linking per Windows usando il linker LLVM di Linux
          lld-link /subsystem:windows /entry:start /out:TinyRetroPad-DarkMode.exe trpad.obj

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: TinyRetroPad-DarkMode-Windows
          path: TinyRetroPad-DarkMode.exe

